# Generated by Django 5.0.7 on 2024-08-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='operator_airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_set', to='airline_app.airline'),
        ),
    ]
